# Generated by Django 4.1.3 on 2022-12-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='prod/profile_img/default.png', upload_to='prod/profile_img/'),
        ),
    ]
