# Generated by Django 4.1.3 on 2022-11-20 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
