# Generated by Django 4.1.3 on 2022-11-23 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-ordered_date'], 'verbose_name': 'cart', 'verbose_name_plural': 'carts'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('user',), 'verbose_name_plural': 'Orders'},
        ),
    ]
