# Generated by Django 4.1.3 on 2022-11-23 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_cart_options_remove_cart_ordered_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
    ]
