# Generated by Django 4.1.3 on 2022-11-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code_produit',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
