# Generated by Django 4.1.3 on 2022-11-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_code_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_ttc',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
