# Generated by Django 4.1.3 on 2022-12-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_price_ttc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormModelMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1024, verbose_name='Full name')),
                ('email', models.EmailField(max_length=1024, verbose_name='Email')),
                ('subject', models.CharField(max_length=1024, verbose_name='Subject')),
                ('message', models.TextField(max_length=1024, verbose_name='Message')),
                ('cc_myself', models.BooleanField(default=False, verbose_name='CC myself')),
            ],
            options={
                'verbose_name': 'Contact form',
                'verbose_name_plural': 'Contact forms',
                'ordering': ('full_name',),
            },
        ),
    ]
