# Generated by Django 4.1.3 on 2022-12-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_contactformmodelmixin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformmodelmixin',
            options={'ordering': ('full_name', 'date_sent'), 'verbose_name': 'Contact form', 'verbose_name_plural': 'Contact forms'},
        ),
        migrations.AddField(
            model_name='contactformmodelmixin',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date sent'),
        ),
    ]
