# Generated by Django 4.1.3 on 2022-12-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_marque_produit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformmodelmixin',
            options={'ordering': ('full_name', 'date_sent', 'email', 'subject', 'message', 'cc_myself'), 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/prod/default.jpg', null=True, upload_to='products/prod/'),
        ),
    ]
