# Generated by Django 4.1.5 on 2023-01-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/prod/default.png', max_length=700, null=True, upload_to='products/prod/'),
        ),
    ]
