# Generated by Django 4.1.5 on 2023-02-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='logo_marque',
            field=models.ImageField(blank=True, default='products/prod/default.png', null=True, upload_to='products/prod/logo/'),
        ),
    ]
