# Generated by Django 4.1.5 on 2023-02-11 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_product_logo_marque'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarqueProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, default='products/prod/default.png', null=True, upload_to='products/prod/logo/')),
            ],
            options={
                'verbose_name': 'marque',
                'verbose_name_plural': 'marques',
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='fabriquant',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.marqueproduct'),
        ),
    ]
