# Generated by Django 4.1.5 on 2023-02-11 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_marqueproduct_product_fabriquant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='logo_marque',
        ),
        migrations.RemoveField(
            model_name='product',
            name='marque_produit',
        ),
    ]
